### PR TITLE
changed to inputstream, added support for paths outside the user-space

### PR DESCRIPTION
**Pull request by decoomanj**
This change is [Reviewable](https://reviewable.io/reviews/neofonie/aiko/7)

### CODE REVIEW

**Comment by decoomanj** [comment]
Added an InputStream to handle files. There could be a problem in ResponseDefinition in the function isBodyIncorrect where the body is shown. This wouldn't make sense if it is a binary.

**Comment by j-musca** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[java/src/main/java/de/neofonie/aiko/yaml/ResponseDefinition.java, line 127 [r1]](https://reviewable.io:443/reviews/neofonie/aiko/7#-KEpStWJKU1wo9QFi3K7:-KEpStWJKU1wo9QFi3K8:15882292) ([raw file](https://github.com/neofonie/aiko/blob/69a9925495feccc8c974b574b033b136ca4a00c8/java/src/main/java/de/neofonie/aiko/yaml/ResponseDefinition.java#L127)):_
Still does not work with images.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/neofonie/aiko/7)_

**Comment by decoomanj** [comment]
Updated the response handling for binaries. We need to improve this by adding more validators.

**Comment by j-musca** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/neofonie/aiko/7)_

**Pull request merged**
